/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as DataRouteImport } from './routes/data'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductCodeRouteImport } from './routes/products.$productCode'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'

const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductCodeRoute = ProductsProductCodeRouteImport.update({
  id: '/products/$productCode',
  path: '/products/$productCode',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/explorer': typeof ExplorerRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/products/$productCode': typeof ProductsProductCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/explorer': typeof ExplorerRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/products/$productCode': typeof ProductsProductCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/explorer': typeof ExplorerRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/products/$productCode': typeof ProductsProductCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/dashboard'
    | '/data'
    | '/explorer'
    | '/customers/$customerId'
    | '/products/$productCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/dashboard'
    | '/data'
    | '/explorer'
    | '/customers/$customerId'
    | '/products/$productCode'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/dashboard'
    | '/data'
    | '/explorer'
    | '/customers/$customerId'
    | '/products/$productCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  DashboardRoute: typeof DashboardRoute
  DataRoute: typeof DataRoute
  ExplorerRoute: typeof ExplorerRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  ProductsProductCodeRoute: typeof ProductsProductCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productCode': {
      id: '/products/$productCode'
      path: '/products/$productCode'
      fullPath: '/products/$productCode'
      preLoaderRoute: typeof ProductsProductCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  DashboardRoute: DashboardRoute,
  DataRoute: DataRoute,
  ExplorerRoute: ExplorerRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  ProductsProductCodeRoute: ProductsProductCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
